### ISSUE TITLE
Adapter requires a sessions to be specific to each operation

### ISSUE THREAD

**Issue by bgood** [cloudspannerecosystem/dynamodb-adapter#28]
Currently the adapter requires that a session get created for each operation that needs to be performed `GetItem`, `Query`, `PutItem`, etc.

It would be better to use the `X-Amz-Target` HTTP Header field in the `/` endpoint of the adapter to determine the operation begin requested and route appropriately .  For example `X-Amz-Target: DynamoDB_20120810.Query` could be handled by `/` and routed to the query handler in the adapter.

_Originally posted by @bgood in https://github.com/cloudspannerecosystem/dynamodb-adapter/pull/27#r663198672_

**Comment by sauravcld** [comment]
Hi @bgood we came to realise this issue just a few days ago and have added a fix for it .. would be pushing that fix in the master branch as soon as we have test written for it.

**Comment by bgood** [comment]
@sauravcld Thanks for the update, I'm available to test and review as you need. Do you have an ETA for the update?

**Comment by sauravcld** [comment]
Hi @bgood , we can push the changes to upstream. Also, we internally have had a discussion about refactors which we would like to have in the code base.

**Comment by bgood** [comment]
Pushing that would be great, so we can start to look at it.

For the refactor items, would you be able to create issues for them.  We can then discuss them and work together on them through the issues.
